package integradora.MenuInventario;

import integradora.Main;
import integradora.Menu;
import integradora.Producto;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

public class MenuInventario extends javax.swing.JFrame {

    /**
     * Creates new form MenuInventario
     */
    public MenuInventario() {
        initComponents();
        ObtenerSecciones();
        ObtenerListaDeProductos();
        
        AgregarCuantas.setColumns(5);
        QuitarCuantas.setColumns(5);
    }
    public void ObtenerSecciones(){
        var lista = Main.Secciones;
        
        System.out.println(Main.Secciones.size());
        Secciones.removeAllItems();
        for (String seccion : lista){
            System.out.println(seccion);
            Secciones.addItem(seccion);
        }
    }
    
    public void ObtenerListaDeProductos(){
        String seccion = "";
        try { seccion = Secciones.getSelectedItem().toString(); }
        catch (Exception e) {
            System.out.println("Error en ObtenerListaDeProductos");
            return;
        }
        
        Main.ObtenerOActualizarLosProductos(seccion);
        
        Productos.removeAllItems();
        try {
            for (Producto producto: Main.Inventario){
                //System.out.println("Se agrego el producto " + producto.Nombre + " \n" + producto);
                Productos.addItem(producto.Nombre);
            }
        } catch (Exception e){
            System.out.println("Error en ObtenerListaDeProductos \n" + e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackToMenu = new javax.swing.JButton();
        ProductoLabel = new javax.swing.JLabel();
        Productos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoPrincipal = new javax.swing.JTextArea();
        AgregarCuantas = new javax.swing.JTextField();
        AgregarUnidades = new javax.swing.JButton();
        QuitarCuantas = new javax.swing.JTextField();
        QuitarUnidades = new javax.swing.JButton();
        AggProductoBoton = new javax.swing.JButton();
        ElimProductoBoton = new javax.swing.JButton();
        SeccionLabel = new javax.swing.JLabel();
        Secciones = new javax.swing.JComboBox<>();
        AgregarSeccion = new javax.swing.JButton();
        EliminarSeccion = new javax.swing.JButton();
        CalcularRestocks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackToMenu.setText("Menu");
        BackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuActionPerformed(evt);
            }
        });

        ProductoLabel.setText("Producto");

        Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosActionPerformed(evt);
            }
        });

        TextoPrincipal.setEditable(false);
        TextoPrincipal.setColumns(20);
        TextoPrincipal.setRows(5);
        jScrollPane1.setViewportView(TextoPrincipal);

        AgregarCuantas.setToolTipText("Introduce cuantas unidades quieres agregar");

        AgregarUnidades.setText("Agregar Unidades");
        AgregarUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUnidadesActionPerformed(evt);
            }
        });

        QuitarCuantas.setToolTipText("Introduce cuantas unidades quieres quitar");

        QuitarUnidades.setText("Quitar Unidades");
        QuitarUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarUnidadesActionPerformed(evt);
            }
        });

        AggProductoBoton.setText("Agregar Producto");
        AggProductoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggProductoBotonActionPerformed(evt);
            }
        });

        ElimProductoBoton.setText("Eliminar Productos");
        ElimProductoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElimProductoBotonActionPerformed(evt);
            }
        });

        SeccionLabel.setText("Seccion");

        Secciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeccionesActionPerformed(evt);
            }
        });

        AgregarSeccion.setText("Agregar Seccion");
        AgregarSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarSeccionActionPerformed(evt);
            }
        });

        EliminarSeccion.setText("Eliminar Secciones");
        EliminarSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarSeccionActionPerformed(evt);
            }
        });

        CalcularRestocks.setText("Calcular Restocks");
        CalcularRestocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularRestocksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AgregarCuantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AgregarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(QuitarCuantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CalcularRestocks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(QuitarUnidades, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SeccionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Secciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(317, 317, 317)
                                .addComponent(BackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ProductoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AgregarSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EliminarSeccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(AggProductoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ElimProductoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeccionLabel)
                    .addComponent(Secciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductoLabel)
                    .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgregarCuantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QuitarCuantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuitarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CalcularRestocks)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AggProductoBoton)
                    .addComponent(ElimProductoBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarSeccion)
                    .addComponent(EliminarSeccion))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);

        setVisible(false);
        dispose();
    }//GEN-LAST:event_BackToMenuActionPerformed

    private void ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosActionPerformed
        ActualizarTexto();
    }//GEN-LAST:event_ProductosActionPerformed

    private void AgregarUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUnidadesActionPerformed
        Producto producto = ObtenerProductoSeleccionado();
        if (producto == null) return;
        
        int unidades = 0;
        try {
            unidades = Integer.parseInt(AgregarCuantas.getText());} 
        catch (Exception e) {
            System.out.println("Hubo un error al intentar acceder cuantas unidades agregar");
            showMessageDialog(null, "Hubo un error al intentar acceder cuantas unidades agregar", "Error", ERROR_MESSAGE);
            return;
        }
        
        unidades += producto.Unidades;
        EjecutarUnComandoALaBaseDeDatos("update " + Secciones.getSelectedItem().toString() + " set unidades = '" + unidades + "' where id = '" + (producto.ID) + "';");
        Main.ObtenerOActualizarLosProductos("productos");
        ActualizarTexto();
    }//GEN-LAST:event_AgregarUnidadesActionPerformed

    private void QuitarUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarUnidadesActionPerformed
        Producto producto = ObtenerProductoSeleccionado();
        if (producto == null) return;
        
        int unidades = 0;
        try {
            unidades = Integer.parseInt(QuitarCuantas.getText());} 
        catch (Exception e) {
            System.out.println("Hubo un error al intentar acceder cuantas unidades quitar");
            showMessageDialog(null, "Hubo un error al intentar acceder cuantas unidades quitar", "Error", ERROR_MESSAGE);
            return;
        }
        
        unidades = producto.Unidades - unidades;
        EjecutarUnComandoALaBaseDeDatos("update " + Secciones.getSelectedItem().toString() + " set unidades = '" + unidades + "' where id = '" + (producto.ID) + "';");
        Main.ObtenerOActualizarLosProductos("productos");
        ActualizarTexto();
    }//GEN-LAST:event_QuitarUnidadesActionPerformed

    private void AggProductoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggProductoBotonActionPerformed
        AgregarProducto agregarProducto = new AgregarProducto();
        
        agregarProducto.menu = this;
        agregarProducto.setVisible(true);
    }//GEN-LAST:event_AggProductoBotonActionPerformed

    private void ElimProductoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElimProductoBotonActionPerformed
        EliminarProducto eliminarProducto = new EliminarProducto();
        
        eliminarProducto.menu = this;
        eliminarProducto.setVisible(true);
    }//GEN-LAST:event_ElimProductoBotonActionPerformed

    private void SeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeccionesActionPerformed
        ObtenerListaDeProductos();
    }//GEN-LAST:event_SeccionesActionPerformed

    private void AgregarSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarSeccionActionPerformed
        AgregarSeccion agregarSeccion = new AgregarSeccion();
        
        agregarSeccion.menu = this;
        agregarSeccion.setVisible(true);
    }//GEN-LAST:event_AgregarSeccionActionPerformed

    private void EliminarSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarSeccionActionPerformed
        EliminarSeccion eliminarSeccion = new EliminarSeccion();
        
        eliminarSeccion.menu = this;
        eliminarSeccion.setVisible(true);
    }//GEN-LAST:event_EliminarSeccionActionPerformed

    private void CalcularRestocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularRestocksActionPerformed
        CalcularReStocks calc = new CalcularReStocks();
        Producto producto = null;
        try { producto = ObtenerProductoSeleccionado(); }
        catch (Exception e) {
            System.out.println("Error en CalcularRestocksActionPerformed \n" + e);
            showMessageDialog(null, "Seleccione un producto", "Error", ERROR_MESSAGE);
            return;
        }
        
        calc.menu = this;
        calc.producto = producto;
        calc.Iniciar();
    }//GEN-LAST:event_CalcularRestocksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInventario().setVisible(true);
            }
        });
    }

    private Producto ObtenerProductoSeleccionado(){
        try { return Main.Inventario.get(Productos.getSelectedIndex());
        } catch (Exception e) { 
            System.out.println("No se pudo obtener producto seleccionado " + e);
            return null; 
        }
    }
    public void ActualizarTexto(){
        Producto producto = ObtenerProductoSeleccionado();
        
        
        TextoPrincipal.selectAll();
        TextoPrincipal.replaceSelection(null);
        if (producto == null) TextoPrincipal.insert("No hay prodcutos en esta seccion", 0);
        else TextoPrincipal.insert(producto.toString(), 0);
        
        
    }
    public void EjecutarUnComandoALaBaseDeDatos(String comando){
        String url = "jdbc:mysql://localhost:3306/servikino",
                usuario = "root",
                contraseña = "";
        
        try (Connection conn = DriverManager.getConnection(url, usuario, contraseña)){
            
            System.out.println("Conexion exitosa a la base de datos");
            
            // Un query es una consulta
            String query = "select * from inventario";
            
            
            try (PreparedStatement stmt = conn.prepareStatement(query)){
                stmt.executeUpdate(comando);
                
            } catch (SQLException e){
                System.out.println("Error al ejectutar el comando: \n" + comando + "\n" + e.getMessage());
            }
            
        } catch (SQLException e){
            System.out.println("Error al conectar a la base de datos" + e.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AggProductoBoton;
    private javax.swing.JTextField AgregarCuantas;
    private javax.swing.JButton AgregarSeccion;
    private javax.swing.JButton AgregarUnidades;
    private javax.swing.JButton BackToMenu;
    private javax.swing.JButton CalcularRestocks;
    private javax.swing.JButton ElimProductoBoton;
    private javax.swing.JButton EliminarSeccion;
    private javax.swing.JLabel ProductoLabel;
    private javax.swing.JComboBox<String> Productos;
    private javax.swing.JTextField QuitarCuantas;
    private javax.swing.JButton QuitarUnidades;
    private javax.swing.JLabel SeccionLabel;
    public javax.swing.JComboBox<String> Secciones;
    private javax.swing.JTextArea TextoPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
