/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package integradora.MenuInventario;

import integradora.Main;
import integradora.Menu;
import integradora.Producto;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author DELL
 */
public class MenuInventario extends javax.swing.JFrame {

    /**
     * Creates new form MenuInventario
     */
    public MenuInventario() {
        initComponents();
        ObtenerListaDeProductos();
        
        AgregarCuantas.setColumns(5);
        QuitarCuantas.setColumns(5);
    }
    public void ObtenerListaDeProductos(){
        var listaProductos = Main.Inventario;
        
        Productos.removeAllItems();
        for (Producto producto: listaProductos){
            //System.out.println("Se agregeo el producto \n" + producto);
            Productos.addItem(producto.Nombre);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackToMenu = new javax.swing.JButton();
        ProductoLabel = new javax.swing.JLabel();
        Productos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoPrincipal = new javax.swing.JTextArea();
        AgregarCuantas = new javax.swing.JTextField();
        AgregarUnidades = new javax.swing.JButton();
        QuitarCuantas = new javax.swing.JTextField();
        QuitarUnidades = new javax.swing.JButton();
        AggProductoBoton = new javax.swing.JButton();
        ElimProductoBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackToMenu.setText("Menu");
        BackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuActionPerformed(evt);
            }
        });

        ProductoLabel.setText("Producto");

        Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductosActionPerformed(evt);
            }
        });

        TextoPrincipal.setEditable(false);
        TextoPrincipal.setColumns(20);
        TextoPrincipal.setRows(5);
        jScrollPane1.setViewportView(TextoPrincipal);

        AgregarCuantas.setToolTipText("Introduce cuantas unidades quieres agregar");

        AgregarUnidades.setText("Agregar Unidades");
        AgregarUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUnidadesActionPerformed(evt);
            }
        });

        QuitarCuantas.setToolTipText("Introduce cuantas unidades quieres quitar");

        QuitarUnidades.setText("Quitar Unidades");
        QuitarUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitarUnidadesActionPerformed(evt);
            }
        });

        AggProductoBoton.setText("Agregar Producto");
        AggProductoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggProductoBotonActionPerformed(evt);
            }
        });

        ElimProductoBoton.setText("Eliminar Productos");
        ElimProductoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElimProductoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(ProductoLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AgregarCuantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AgregarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(QuitarCuantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(QuitarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AggProductoBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ElimProductoBoton)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductoLabel)
                            .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AgregarCuantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(QuitarCuantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QuitarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgregarUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AggProductoBoton)
                    .addComponent(ElimProductoBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);

        setVisible(false);
        dispose();
    }//GEN-LAST:event_BackToMenuActionPerformed

    private void ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductosActionPerformed
        ActualizarTexto();
    }//GEN-LAST:event_ProductosActionPerformed

    private void AgregarUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUnidadesActionPerformed
        Producto producto = ObtenerProductoSeleccionado();
        if (producto == null) return;
        
        int unidades = 0;
        try {
            unidades = Integer.parseInt(AgregarCuantas.getText());} 
        catch (Exception e) {
            System.out.println("Hubo un error al intentar acceder cuantas unidades agregar");
            showMessageDialog(null, "Hubo un error al intentar acceder cuantas unidades agregar", "Error", ERROR_MESSAGE);
            return;
        }
        
        unidades += producto.Unidades;
        EjecutarUnComandoALaBaseDeDatos("update inventario set unidades = '" + unidades + "' where id = '" + (producto.ID) + "';");
        Main.ObtenerOActualizarLosProductos();
        ActualizarTexto();
    }//GEN-LAST:event_AgregarUnidadesActionPerformed

    private void QuitarUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitarUnidadesActionPerformed
        Producto producto = ObtenerProductoSeleccionado();
        if (producto == null) return;
        
        int unidades = 0;
        try {
            unidades = Integer.parseInt(QuitarCuantas.getText());} 
        catch (Exception e) {
            System.out.println("Hubo un error al intentar acceder cuantas unidades quitar");
            showMessageDialog(null, "Hubo un error al intentar acceder cuantas unidades quitar", "Error", ERROR_MESSAGE);
            return;
        }
        
        unidades = producto.Unidades - unidades;
        EjecutarUnComandoALaBaseDeDatos("update inventario set unidades = '" + unidades + "' where id = '" + (producto.ID) + "';");
        Main.ObtenerOActualizarLosProductos();
        ActualizarTexto();
    }//GEN-LAST:event_QuitarUnidadesActionPerformed

    private void AggProductoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggProductoBotonActionPerformed
        AgregarProducto agregarProducto = new AgregarProducto();
        
        agregarProducto.menu = this;
        agregarProducto.setVisible(true);
    }//GEN-LAST:event_AggProductoBotonActionPerformed

    private void ElimProductoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElimProductoBotonActionPerformed
        EliminarProducto eliminarProducto = new EliminarProducto();
        
        eliminarProducto.menu = this;
        eliminarProducto.setVisible(true);
    }//GEN-LAST:event_ElimProductoBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInventario().setVisible(true);
            }
        });
    }

    private Producto ObtenerProductoSeleccionado(){
        try { return Main.Inventario.get(Productos.getSelectedIndex());
        } catch (Exception e) { 
            System.out.println("No se pudo obtener producto seleccionado " + e);
            return null; 
        }
    }
    public void ActualizarTexto(){
        Producto producto = ObtenerProductoSeleccionado();
        if (producto == null) return;
        
        TextoPrincipal.selectAll();
        TextoPrincipal.replaceSelection(null);
        TextoPrincipal.insert(producto.toString(), 0);
    }
    public void EjecutarUnComandoALaBaseDeDatos(String comando){
        String url = "jdbc:mysql://localhost:3306/servikino",
                usuario = "root",
                contraseña = "";
        
        try (Connection conn = DriverManager.getConnection(url, usuario, contraseña)){
            
            System.out.println("Conexion exitosa a la base de datos");
            
            // Un query es una consulta
            String query = "select * from inventario";
            
            
            try (PreparedStatement stmt = conn.prepareStatement(query)){
                stmt.executeUpdate(comando);
                
            } catch (SQLException e){
                System.out.println("Error al ejectutar el comando: \n" + comando + "\n" + e.getMessage());
            }
            
        } catch (SQLException e){
            System.out.println("Error al conectar a la base de datos" + e.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AggProductoBoton;
    private javax.swing.JTextField AgregarCuantas;
    private javax.swing.JButton AgregarUnidades;
    private javax.swing.JButton BackToMenu;
    private javax.swing.JButton ElimProductoBoton;
    private javax.swing.JLabel ProductoLabel;
    private javax.swing.JComboBox<String> Productos;
    private javax.swing.JTextField QuitarCuantas;
    private javax.swing.JButton QuitarUnidades;
    private javax.swing.JTextArea TextoPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
